name: Build and Release to npm registry

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow when a new version tag (e.g., v1.0.0) is pushed

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build the package
        run: npm run build

      - name: Publish package to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
